name: cambio_chaco_app
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencias necesarias
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true

  # Archivos de assets
  assets:
    - assets/
    - assets/cambio_chaco_assets/
    - assets/general_icons/
    - assets/general_icons/menu_drawer/
    - assets/flags_iso/16/
    - assets/flags_iso/24/
    - assets/flags_iso/32/
    - assets/flags_iso/48/
    - assets/flags_iso/64/
    - assets/flags_iso/128/


  # Configuración de internacionalización
  generate: true 
flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: intl_en.arb
  output-class: AppLocalizations
